version: '3.3'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - '127.0.0.1:3000:3000'
    command: 'yarn start'
